### ISSUE TITLE
code source

### ISSUE THREAD

**Issue by Moayadkh** [TomLany/NOAA-Weather-Grabber#2]
I think this link is helpful to find 4-letter-codes as well:
https://www.world-airport-codes.com/alphabetical/country-name/u.html

**Comment by TomLany** [comment]
@Moayadkh: Thanks for the comment! Glad you found this script, and another resource for finding 4-letter airport codes. I prefer to link to official government documentation in the plugin readme, but do appreciate knowing about other resources for finding this information.
