### ISSUE TITLE
How do I use the images?

### ISSUE THREAD

**Issue by jrnichols** [TomLany/NOAA-Weather-Grabber#6]
I have the script mostly working, but I can't figure out how to get it to show the images from imgCode. It's showing the right output, but I'd love to get it to display one of the images. 

Image code: day/skc

I see in the script it has "$imgCode = explode( 'weather.gov/icons/land/', $imgCode );"

but if I try to hit https://weather.gov/icons/land/day/skc.png with curl, I get a 301 Moved Permanently error. 

Is it supposed to pull the images remotely or use the local ones?  Thanks!

**Comment by TomLany** [comment]
Hi @tacobob,

Glad to hear you're using this script!

I use these images stored locally on my site, as this offers more flexibility and limits problems if/when NOAA moves images files on their site.

I use the code below to embed the local versions of these images on my site. You just need to specify the file path (update this for your site), add the imgCode, then add the png file extension. 

`echo '<img src="/LOCATION-OF-LOCAL-IMAGES/' . $weather->imgCode . '.png" width="60" height="60" />';`

Does this work for you?

Also, I just pushed a small update to this script to match updates NOAA made to their API. Feel free to check that out. Thanks!

**Comment by jrnichols** [comment]
Sorry for the delay, the machine I'm testing it on is at work and I've been off a few days. 

Yes, that did work! It's now displaying images. That works great. :) And I did update to the newest version, and things are working as expected. Thanks!

**Comment by TomLany** [comment]
@tacobob Glad it's working now!
